  
version: '3.7'

services:
  # starts docker container running minio server instance.
  # minio server's web interface will be accessible on the host at port 9000.
  minio1:
    network_mode: host
    image: minio/minio:RELEASE.2020-09-05T07-14-49Z
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
    command: gateway s3

  sniffer:
    network_mode: host
    image: seekret/sniffer:1.3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      ROTATION_SECONDS: 10
      S3_URL: http://localhost:9000/
      BUCKET_NAME: ${BUCKET_NAME}
      FOLDER_NAME: ${FOLDER_NAME}
      PREFIX: ${PREFIX} 
      MAX_FILE_SIZE: 100
      BPF_FILTER: ${BPF_FILTER}

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio_data:
    driver: local
