# Default values for seekret.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: seekret-sidecar-injector
image: seekret/sniffer:2

# Injector values
injector:
  annotationNamespace: injector.seekret.com
  imageName: tumblr/k8s-sidecar-injector:latest
  namespace: seekret-injector
  createNamespace: true
  customSidecarCert:
  customSidecarKey:
  customSidecarCa:

# Sniffer values
bucket:
  provider: gcs
  name:
  folderName: default/captures
  accessKey:
  secretKey:


rotationSeconds: 600
bpfFilter: "tcp and not tcp port 443"
maxFileSize: 50


httpProxyClient:
  enabled: false
  image: seekret/http-proxy-client:1
  target:
  pullIntervalInSeconds: 10
  gcs:
    projectName:
    bucketName:
    credsFile: "/seekret/gcscreds.json"

gcsCredentials:
  name: seekret-gcscreds
  creds:

sniffer:
  requestCpu: "100m"
  requestMemory: "100Mi"
  limitCpu: "500m"
  limitMemory: "256Mi"

tlsProxy:
  enabled: false
  certsSecretName: seekret-tls-proxy-certs
  adminPort: 9901
  targetAddress: localhost
  targetPort: 443
  envoyImage: seekret/envoy-https-proxy:1
  initImage: seekret/https-proxy-init:1
  requestCpu: "100m"
  requestMemory: "50Mi"
  limitCpu: "500m"
  limitMemory: "256Mi"

networkPolicy:
  enabled: false
