# Default values for seekret.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: seekret-sidecar-injector
# Injector values
injector:
  annotaionNamespace: injector.seekret.com
  imageName: tumblr/k8s-sidecar-injector:latest

# Minio values
s3:
  bucketName: seekret
  folderName: pcaps
  s3_url: http://seekret-minio.seekret:9000

# Dumper values
rotationSeconds: 1800
bpfFilter: "not tcp port 9000"
maxFileSize: 100

# Values for minio dependency
minio:
  ## Set default accesskey, secretkey
  ##
  accessKey: "seekret"
  secretKey: "seekret123"

  replicas: 2

  persistence:
    size: "10Gi"
  ## Create a bucket after minio install
  ##

  resources:
    requests:
      memory: "2Gi"

  s3gateway:
    enabled: false
    replicas: 2
    serviceEndpoint:
    accessKey:
    secretKey:

  gcsgateway:
    enabled: true
    gcsKeyJson:
    projectId:

httpProxyClient:
  enabled: false
  image: seekret/http-proxy-client:1
  target:
  pullIntervalInSeconds: 10
  gcs:
    projectName:
    bucketName:
    credsFile: "/seekret/gcscreds.json"

gcsCredentials:
  name: seekret-gcscreds
  creds:

tlsProxy:
  enabled: false
  certsSecretName: seekret-tls-proxy-certs
  adminPort: 9901
  targetAddress: localhost
  targetPort: 443
  envoyImage: seekret/envoy-https-proxy:1
  initImage: seekret/https-proxy-init:1
