# Default values for seekret.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: seekret-sidecar-injector
image: seekret/sniffer:1
# Injector values
injector:
  annotaionNamespace: injector.seekret.com
  imageName: tumblr/k8s-sidecar-injector:latest

# Sniffer values
s3:
  bucketName:
  folderName: default/captures
  ## Default url to communicate with GCS buckets
  s3URL: https://storage.googleapis.com
  ## Use HMAC key auth instead of role based
  keyAuth: true
  ## Set accessKey, secretKey
  accessKey:
  secretKey:
  ##default region for buckets
  region: us-central1


rotationSeconds: 1800
bpfFilter: "tcp and not tcp port 443"
maxFileSize: 100


httpProxyClient:
  enabled: false
  image: seekret/http-proxy-client:1
  target:
  pullIntervalInSeconds: 10
  gcs:
    projectName:
    bucketName:
    credsFile: "/seekret/gcscreds.json"

gcsCredentials:
  name: seekret-gcscreds
  creds:

tlsProxy:
  enabled: false
  certsSecretName: seekret-tls-proxy-certs
  adminPort: 9901
  targetAddress: localhost
  targetPort: 443
  envoyImage: seekret/envoy-https-proxy:1
  initImage: seekret/https-proxy-init:1
