{{ if .Values.s3.keyAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3.secretName }}
type: Opaque
data:
  accessKey: {{required "An access key ID is required with keyAuth authentication!" .Values.s3.accessKey | b64enc }}
  secretKey: {{required "A secret key is required with keyAuth authentication!" .Values.s3.secretKey | b64enc }}
{{ end }}
