{{ if .Values.httpProxyClient.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gcsCredentials.name }}
type: Opaque
data:
  creds:
    {{ required ".Values.gcsCredentials.creds is required" .Values.gcsCredentials.creds | b64enc }}
{{ end }}
