{{ if .Values.httpProxyClient.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-proxy-client
spec:
  selector:
    matchLabels:
      app: http-proxy-client
  template:
    metadata:
      labels:
        app: http-proxy-client
    spec:
      volumes:
        - name: {{ .Values.gcsCredentials.name | quote }}
          secret:
            secretName: {{ .Values.gcsCredentials.name | quote }}
      containers:
        - name: http-proxy-client
          image: {{ .Values.httpProxyClient.image | quote }}
          imagePullPolicy: Always
          args:
            - {{ required ".Values.httpProxyClient.target must be a valid URL address" .Values.httpProxyClient.target | quote }}
            - {{ required ".Values.httpProxyClient.gcs.projectName is required" .Values.httpProxyClient.gcs.projectName | quote }}
            - {{ required ".Values.httpProxyClient.gcs.bucketName is required" .Values.httpProxyClient.gcs.bucketName | quote }}
            - "--interval"
            - {{ .Values.httpProxyClient.pullIntervalInSeconds | quote }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: {{ .Values.httpProxyClient.gcs.credsFile | quote }}
          volumeMounts:
            - name: {{ .Values.gcsCredentials.name | quote }}
              mountPath: {{ .Values.httpProxyClient.gcs.credsFile | quote }}
              subPath: creds
              readOnly: true
      restartPolicy: Always
{{ end }}
