name: helm sanity

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ 'master' ]
  workflow_dispatch:
    branches: [ '**' ]

jobs:
  helm_sanity:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: start minikube
        id: minikube
        uses: manusa/actions-setup-minikube@v2.0.1
        with:
          minikube version: 'v1.13.1'
          kubernetes version: 'v1.19.2'

      - uses: azure/setup-helm@v1

      - name: run tests
        run: |
          cd tests
          ./test_helm.sh ${{ secrets.ACCESS_KEY }} ${{ secrets.SECRET_KEY }} ${{ secrets.BUCKET }} -v
